version: "3.8"

services:
  localstack:
    container_name: "home_localstack_main"
    image: localstack/localstack
    ports:
      - "0.0.0.0:4566:4566"            # LocalStack Gateway
      - "0.0.0.0:4510-4559:4510-4559"  # external services port range
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=Passw0rd
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
