name: Serverless user app CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          registry-url: https://npm.pkg.github.com/
          cache: "npm"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PACKAGE_PAT}}
      - run: npm run lint

  build-and-test:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.17.0, 20.5.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Run build if present
        run: npm run build --if-present

      - name: Run tests
        run: npm test
