service: aws-serverless-user-app-api

frameworkVersion: "3"

plugin:
  - serverless-esbuild
  - serverless-localstack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs.18.x
  region: us-east-1
  apiGateWay:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environement:
    AWS_NODEJS_CONNECTION_REUSE_ENABLE: "1"
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    DYNAMODB_TABLE: "${self:service}-${opt:stage, self:provider.stage}"
  iam:
    statsments:
      - Effect: "Allow"
        Action:
          - "Dynamodb:DescribeTable"
          - "Dynamodb:Query"
          - "Dynamodb:Scan"
          - "Dynamodb:GetItem"
          - "Dynamodb:PutItem"
          - "Dynamodb:UpdateItem"
          - "Dynamodb:DeleteItem"
        Resources: "arn:aws:dyanmodb:${opt:region, self:provider.region}:*:/table${self:provider.environment.DYNAMODB_TABEL}"
  lambdaHashingVersion: "20201221"

functions:
  hello:
    handler: src/function/healthcheck.handler
    events:
      - http:
        path: healthcheck/ping
        method: get
        cors: true
  # signup:
  #   handler: src/function/signup.handler
  #   events:
  #     - http:
  #         path: auth/signup
  #         method: post
  #         cors: true

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: "node16"
    define:
      "require.resolve": undefined
    platform: "node"
    concurrency: 10

  dynamodb:
    start:
      port: 8000
      inMemory: true
      docker: true
      noStart: true
    stage: dev

  "serverles:offline":
    httpPort: 5000
    babelOptions:
      presets: ["env"]

  localstack:
    stages:
      - local
    lambda:
      mountCode: true
    docker:
      sudo: true
    autoStart: true

resources:
  Resources:
    UserTable:
      type: "AWS:DynamoDB:TABLE"
    Properties:
      TableName: "UsersTable"
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
    ProvisionedThroughPut:
      ReadCapacityUnits: 1
      WriteCapacitUnits: 1
